### ISSUE TITLE
Stemming Strategy should be in update() and parse_query()

### ISSUE THREAD

**Issue by jrast** [notanumber/xapian-haystack#141] opened 2015-01-09 22:40 UTC
I'm very new to search, but as I understand, the stemming strategy should be set in both, `XapianSearchBackend.search()` and `XapianSearchBackend.parse_query()`. At the moment it is only set in `parse_query()` which leads (at least in my case) to very bad results.

In my opinion the stemming strategy should be made configurable in the settings and should have a good default. Here is the question if `STEM_SOME` is the right choice as default. `STEM_SOME` means that words starting with a uppercase letter (among some other special constructs) are not stemmed which is, again in my opinion, not the prefered way if you are indexing a language in which nouns start with an uppercase letter. More information about the stemming strategies can be found [here in the Xapian Doc](http://xapian.org/docs/apidoc/html/classXapian_1_1QueryParser.html#ac7dc3b55b6083bd3ff98fc8b2726c8fd).

If this is realy a bug, I'm willing to implement the configurable stemming strategy. If it's configurable we can discuss about the default which should be used.

**Comment by jorgecarleitao** [comment] 2015-01-09 22:50
Thanks @jrast for using Xapian, and for bringing this here.

I agree it may be a bug. I would be completely convinced if you can provide a test case showing that this leads to an unexpected behaviour for the user :-) 

In principle this can be tested by indexing a word that can be stemmed (e.g. `connection` ([stem](http://xapian.org/docs/stemming.html) `connect`), and search for the stem (`connect`). In this situation, your prediction (that you report here as a bug) is that the result is not found when it should, right? (i.e. did I understood this issue correctly?)

**Comment by jrast** [comment] 2015-01-10 16:39
In pull request #142 I have added a simple test with some notes which shows the behaviour which in my opinion is a bug.

**Comment by jrast** [comment] 2015-01-10 19:11
Ok, I extended the test and updated the pull request so it matches better my setup in which the error occour. As you can see in the second test, I try to search for a part of the word `Plattenkreuz`. If i enter the search term like `Plat`, the document is found, but if I search for `plat` the term is not found.

**Comment by jorgecarleitao** [comment] 2015-01-11 00:21
Yap, I'm convinced. Nice catch and thanks for reporting it.

**Comment by jrast** [comment] 2015-01-11 00:56
But I'm no longer shure if the error has its cause in the stemming or if
the bug is more related to the EdgeNgram field I'm using.

If you can give me some hints, I can try to fix and test this, so the pull
request can be merged. But I'm very new to xapian and haystack, so it might
be better to see a solution from someone else and learn from this for
future contributions.
Am 11.01.2015 01:21 schrieb "jorgecarleitao" <notifications@github.com>:

**Comment by jorgecarleitao** [comment] 2015-01-12 18:46
Ok. I studied this problem, and stemming seems to be working correctly. In your case of the `Plattenkreuz`, it is expected behaviour:

> STEM_SOME: Stem all terms except for those which start with a capital letter, or are followed by certain characters (currently: (/@<>=*[{" ), or are used with operators which need positional information. 

However, we currently don't support choosing the stemming strategy, and I think that is the issue here. I believe this should be implemented. I think we need to:

- add new global option to pass the stemming strategy to Xapian.
- adapt the code to receive this option (like we do for the stemming language)

I'm thus changing this to feature.

**Comment by jrast** [comment] 2015-01-12 18:52
In the current code, the stemming startegy is only set in `parse_query()` but not in `update()` should this be fixed too or is this by intention?

**Comment by jorgecarleitao** [comment] 2015-01-12 18:56
It is technically wrong, but has no implications (since `STEM_SOME` is the default in Xapian). Yes, it should be fixed. :-)

**Closed** 2015-01-12 21:39 UTC
Labels: Feature
